### ISSUE TITLE
Allow local Album art

### ISSUE THREAD

**Issue by corngoblin** [patryk-ku/mpris-discord-rpc#10]
Would it be possible to pull the album art directly from MPRIS?

Some songs are named slightly different than what would be on lastfm so nothing will show.

Thank you for your time.

**Comment by patryk-ku** [comment]
Hello.

It is not possible to display local images, only external URLs. This is specified in the Discord documentation here:
https://discord.com/developers/docs/rich-presence/overview#assets

Theoretically I could add a backup album image from MusicBrainz but usually if there is no cover art on Last.fm then most likely there won't be on MusicBrainz either because as I know Last.fm pulls album data from MusicBrainz.

So the only option is to either change the album name to match the name on Last.fm, or add the missing album covers on Last.fm yourself. When I see that an album I'm listening to doesn't have a cover, I usually add it by myself.

**Comment by corngoblin** [comment]
You know, that makes the way you did it make way more sense now. Lol

Thank you for answering my question.
