### ISSUE TITLE
Time + Elapsed and left

### ISSUE THREAD

**Issue by bouboulov** [patryk-ku/mpris-discord-rpc#5]
First of all, thanks for this plugin. This is the most beautiful and complete Discord RPC I've tried so far.

I wanted to ask a little, maybe silly question : when playing, the song indicates the time - which I think is quite good - but also "elaspsed" or "left", according to your presentation though I diden't find how to set it to "left". 

I was thinking about an option to remove these "elapsed" or "left" words to just have the timestamp, maybe in the call of the app. Or perhaps it's just in MPRIS, I don't really know, that's the first time I use it too.

I went through the code and searched on Chat GPT for ansewers but nothing worked, as I'm just somekind of a beginner in this stuff.

That's all, if you have this in project or some tweaks we could switch in the code or maybe documentation to set these, that would be useful.

Keep up the good work ! BBV

**Comment by patryk-ku** [comment]
Hello @bouboulov, thanks for your kind words.

It is not possible to change the caption that is displayed next to the time or display only timer, it's a hard coded design from Discord.

And yes, you can choose between "elapsed" and "left". The [cargo package](https://crates.io/crates/discord-rich-presence) I used to create the Discord RPC provides two options for Timestamp: .start() or .end(). Unfortunately but I couldn't get it to show the "left" time correctly, only the "elapsed". Not sure if I did something wrong or there is a bug in this package. For now it works this way: script will use current song time if the music player provides this information via MPRIS. If not it will use time of last track change. If you pause the song then it's set to 0 seconds "left" and it will return to previous "elapsed" time if you continue playback. I was thinking about working on it a bit more but decided it wasn't that important.

If you want I can add an additional parameter to disable the display of the time completely, it's not a problem. Or I can try to add option to chose between time left or elapsed if I can figure out how to do it correctly.

PS. I'm not going to lie but I don't know Rust very well. Basically, I wrote this program after reading a few chapters of the rustbook. I first wrote it in [JavaScript](https://github.com/patryk-ku/node-music-discord-rpc) but it's not the best language for writing such things. I wanted it to be as lightweight as possible so I picked Rust because it's way faster.

And by the way, I wrote this because there wasn't or couldn't find any better alternative. But I have recently discovered at least one. Check out [THIS](https://github.com/lazykern/mprisence) maybe you will like it more. The person who wrote this looks like he has more experience with Rust and writing Linux software in general. His script is available in AUR and he also has a setup for systemd so that you don't have to manually add the script to the autostart, it just runs automatically.

The funny thing is that I discovered his work only because the person who wrote it was the first person to star my project, no Idea why he starred it while his is way better.
